# What happens when you run the following program? Why do we get that result?

def set_foo():
    foo = 'bar'

set_foo()
print(foo)

# Solution: Will raise NameError exception as foo is undefined. When you invoke 
# the set_foo function it initialises foo variable assigning it the value 'bar' 
# and then returns none.
# When the foo variable is passed to print function it raises an exception
# because the variable is local to the function and not available to be passed
# to print function.